<?php

use Illuminate\Database\Seeder;
use App\Area;
use App\Observation;
use LaravelEnso\PermissionManager\app\Models\Permission;

class ObservationSeeder extends Seeder
{
  private const Observations = [

    ['order' => 10, 'area_name' => "Self Awareness", "key" => "sa1", 'name' => "I know I am a unique individual and can tell you what I am like."],
    ['order' => 20, 'area_name' => "Self Awareness", "key" => "sa2", 'name' => "I know my strengths and I feel good about them."],
    ['order' => 30, 'area_name' => "Self Awareness", "key" => "sa3", 'name' => "I know the things I find hard and I can try to get better at them."],
    ['order' => 40, 'area_name' => "Self Awareness", "key" => "sa4", 'name' => "I can tell when I feel proud of myself and I like it when others praise me."],
    ['order' => 50, 'area_name' => "Self Awareness", "key" => "sa5", 'name' => "I know what is important to me and can listen to what other people want from me."],
    ['order' => 60, 'area_name' => "Self Awareness", "key" => "sa6", 'name' => "I can think about my actions and can learn from them."],
    ['order' => 70, 'area_name' => "Self Awareness", "key" => "sa7", 'name' => "I can make sense of what has happened to me and understand how this makes me feel."],
    ['order' => 80, 'area_name' => "Self Awareness", "key" => "sa8", 'name' => "I can tell what I am feeling and can say how I am feeling."],
    ['order' => 90, 'area_name' => "Self Awareness", "key" => "sa9", 'name' => "I know that feelings sometimes 'take over' and know what makes me feel angry or upset."],
    ['order' => 100, 'area_name' => "Self Awareness", "key" => "sa10", 'name' => "I can tell how I am likely to think, feel and behave in different situations."],
    ['order' => 110, 'area_name' => "Self Awareness", "key" => "sa11", 'name' => "I can tell when I have conflicting feelings and know how to cope with this."],
    ['order' => 120, 'area_name' => "Self Awareness", "key" => "sa12", 'name' => "I can use my past experience to make wise choices to plan what to do with learning and relationships."],

    ['order' => 10, 'area_name' => "Managing Feelings", "key" => "mf13", 'name' => "I can express my feelings clearly and openly and appropriately in different situations."],
    ['order' => 20, 'area_name' => "Managing Feelings", "key" => "mf14", 'name' => "I know that how I express my feelings makes a difference to other people and what happens to me."],
    ['order' => 30, 'area_name' => "Managing Feelings", "key" => "mf15", 'name' => "I know some ways to manage strong feelings so that I do not hurt myself and other people."],
    ['order' => 40, 'area_name' => "Managing Feelings", "key" => "mf16", 'name' => "I know what makes me feel good and how to help have a good time in ways that don't hurt myself or other people."],
    ['order' => 50, 'area_name' => "Managing Feelings", "key" => "mf17", 'name' => "I know that how I feel makes a difference to my health and know how to keep myself well and happy."],
    ['order' => 60, 'area_name' => "Managing Feelings", "key" => "mf18", 'name' => "I can reduce, manage or change strong and uncomfortable feelings such as anger, anxiety, stress and jealousy."],

    ['order' => 10, 'area_name' => "Motivation", "key" => "mo19", 'name' => "I can set myself a goal or challenge and know when I have been successful."],
    ['order' => 20, 'area_name' => "Motivation", "key" => "mo20", 'name' => "I can break a long-term plan into small steps."],
    ['order' => 30, 'area_name' => "Motivation", "key" => "mo21", 'name' => "I can anticipate and plan to work around or overcome potential obstacles."],
    ['order' => 40, 'area_name' => "Motivation", "key" => "mo22", 'name' => "I can monitor and evaluate my own performance."],
    ['order' => 50, 'area_name' => "Motivation", "key" => "mo23", 'name' => "I can work towards long-term goals and can wait for a reward."],
    ['order' => 60, 'area_name' => "Motivation", "key" => "mo24", 'name' => "I know how to bring about change in myself and others."],
    ['order' => 70, 'area_name' => "Motivation", "key" => "mo25", 'name' => "I know that mistakes are a part of learning and can bounce back when I feel disappointed or have failed."],
    ['order' => 80, 'area_name' => "Motivation", "key" => "mo26", 'name' => "I can tell when my feelings are getting in the way of learning and know what to do about it."],
    ['order' => 90, 'area_name' => "Motivation", "key" => "mo27", 'name' => "I can attend well and can ignore distractions."],
    ['order' => 100, 'area_name' => "Motivation", "key" => "mo28", 'name' => "I can think about what I have done and learn from my mistakes."],
    ['order' => 110, 'area_name' => "Motivation", "key" => "mo29", 'name' => "I can stay optimistic and am positive when I try something new."],
    ['order' => 120, 'area_name' => "Motivation", "key" => "mo30", 'name' => "I can take responsibility for myself and my actions."],

    ['order' => 10, 'area_name' => "Empathy", "key" => "em31", 'name' => "I can tell how people are feeling."],
    ['order' => 20, 'area_name' => "Empathy", "key" => "em32", 'name' => "I know that people express their feelings in different ways but that we all have feelings."],
    ['order' => 30, 'area_name' => "Empathy", "key" => "em33", 'name' => "I can tell what other people might be feeling or thinking."],
    ['order' => 40, 'area_name' => "Empathy", "key" => "em34", 'name' => "I can listen to others and I can help them feel better if they are feeling worried or unhappy."],
    ['order' => 50, 'area_name' => "Empathy", "key" => "em35", 'name' => "I respect people from different cultures and backgrounds."],
    ['order' => 60, 'area_name' => "Empathy", "key" => "em36", 'name' => "I know the impact of bullying, prejudice and discrimination on others."],
    ['order' => 70, 'area_name' => "Empathy", "key" => "em37", 'name' => "I can support others with their problems."],
    ['order' => 80, 'area_name' => "Empathy", "key" => "em38", 'name' => "I can feel empathy for others and do things to help."],
    ['order' => 90, 'area_name' => "Empathy", "key" => "new", 'name' => "I understand and accept that the feelings, beliefs and values of other people are important to them."],
    ['order' => 100, 'area_name' => "Empathy", "key" => "new", 'name' => "I can see the world from another person’s point of view"],
    ['order' => 110, 'area_name' => "Empathy", "key" => "new", 'name' => "I can work out how people are feeling through their words, body language, gestures and tone, and pay attention to them."],
    ['order' => 120, 'area_name' => "Empathy", "key" => "new", 'name' => "I have a range of strategies to respond effectively in ways that can help others feel better."],

    ['order' => 10, 'area_name' => "Social Skills", "key" => "ss39", 'name' => "I can communicate with others, listen to them and express my thoughts and feelings."],
    ['order' => 20, 'area_name' => "Social Skills", "key" => "ss40", 'name' => "I can manage my relationships and take account of what other people are thinking and feeling."],
    ['order' => 30, 'area_name' => "Social Skills", "key" => "ss41", 'name' => "I can make wise choices about my relationships."],
    ['order' => 40, 'area_name' => "Social Skills", "key" => "ss42", 'name' => "I can make, keep and break friendships without hurting others."],
    ['order' => 50, 'area_name' => "Social Skills", "key" => "ss43", 'name' => "I can work and learn well in groups and take on different roles."],
    ['order' => 60, 'area_name' => "Social Skills", "key" => "ss44", 'name' => "I know my rights and responsibilities in the many groups I belong to (family, school, friends etc.)"],
    ['order' => 70, 'area_name' => "Social Skills", "key" => "ss45", 'name' => "I can act independently and keep my friends."],
    ['order' => 80, 'area_name' => "Social Skills", "key" => "ss46", 'name' => "I can give feedback to others and can listen to and use feedback from them."],
    ['order' => 90, 'area_name' => "Social Skills", "key" => "ss47", 'name' => "I can solve problems and resolve conflicts with other people."],
    ['order' => 100, 'area_name' => "Social Skills", "key" => "ss48", 'name' => "I can tell when I have been successful or unsuccessful in solving a problem and can make wise choices."],
    ['order' => 110, 'area_name' => "Social Skills", "key" => "ss49", 'name' => "I know how to make up with others when we have fallen out."],
    ['order' => 120, 'area_name' => "Social Skills", "key" => "ss50", 'name' => "I can be assertive when appropriate."],

    ['order' => 10, 'area_name' => "Task Orientation", "key" => "to1", 'name' => "Does not refuse to work."],
    ['order' => 20, 'area_name' => "Task Orientation", "key" => "to2", 'name' => "Starts on time."],
    ['order' => 30, 'area_name' => "Task Orientation", "key" => "to3", 'name' => "Not distracted by internal events."],
    ['order' => 40, 'area_name' => "Task Orientation", "key" => "to4", 'name' => "Not distracted by external events."],
    ['order' => 50, 'area_name' => "Task Orientation", "key" => "to5", 'name' => "Copes well with task frustration."],
    ['order' => 60, 'area_name' => "Task Orientation", "key" => "to6", 'name' => "Does not begin task impulsively without understanding."],
    ['order' => 70, 'area_name' => "Task Orientation", "key" => "to7", 'name' => "Shows interest/motivation toward task."],
    ['order' => 80, 'area_name' => "Task Orientation", "key" => "to8", 'name' => "Willing to try new work."],
    ['order' => 90, 'area_name' => "Task Orientation", "key" => "to9", 'name' => "Does not avoid work by loss/abuse of task material."],
    ['order' => 100, 'area_name' => "Task Orientation", "key" => "to10", 'name' => "Shows confidence task-wise."],
    ['order' => 110, 'area_name' => "Task Orientation", "key" => "to11", 'name' => "Acceptable level of error."],
    ['order' => 120, 'area_name' => "Task Orientation", "key" => "to12", 'name' => "Corrects work when asked."],
    ['order' => 130, 'area_name' => "Task Orientation", "key" => "to13", 'name' => "Does not require too much help."],
    ['order' => 140, 'area_name' => "Task Orientation", "key" => "to14", 'name' => "Accepts help from teacher."],
    ['order' => 150, 'area_name' => "Task Orientation", "key" => "to15", 'name' => "Asks for help when needed."],
    ['order' => 160, 'area_name' => "Task Orientation", "key" => "to16", 'name' => "Well presented/organised work."],
    ['order' => 170, 'area_name' => "Task Orientation", "key" => "to17", 'name' => "Well organised desk/materials."],
    ['order' => 180, 'area_name' => "Task Orientation", "key" => "to18", 'name' => "Completes task in given time."],

    ['order' => 10, 'area_name' => "Classroom Conformity", "key" => "cc1", 'name' => "Stays in school."],
    ['order' => 20, 'area_name' => "Classroom Conformity", "key" => "cc2", 'name' => "Attends required lessons."],
    ['order' => 30, 'area_name' => "Classroom Conformity", "key" => "cc3", 'name' => "Stays in class."],
    ['order' => 40, 'area_name' => "Classroom Conformity", "key" => "cc4", 'name' => "Is on time to lessons."],
    ['order' => 50, 'area_name' => "Classroom Conformity", "key" => "cc5", 'name' => "Enters classroom appropriately."],
    ['order' => 60, 'area_name' => "Classroom Conformity", "key" => "cc6", 'name' => "Stays in seat in class."],
    ['order' => 70, 'area_name' => "Classroom Conformity", "key" => "cc7", 'name' => "Sits appropriately in seat in class."],
    ['order' => 80, 'area_name' => "Classroom Conformity", "key" => "cc8", 'name' => "Uses school equipment appropriately."],
    ['order' => 90, 'area_name' => "Classroom Conformity", "key" => "cc9", 'name' => "Raises hand when requiring help."],
    ['order' => 100, 'area_name' => "Classroom Conformity", "key" => "cc10", 'name' => "Does not disrupt class if they have to wait."],
    ['order' => 110, 'area_name' => "Classroom Conformity", "key" => "cc11", 'name' => "Is not verbally inappropriate to teacher."],
    ['order' => 120, 'area_name' => "Classroom Conformity", "key" => "cc12", 'name' => "Is not physically inappropriate to teacher."],
    ['order' => 130, 'area_name' => "Classroom Conformity", "key" => "cc13", 'name' => "Is not over-active in class."],
    ['order' => 140, 'area_name' => "Classroom Conformity", "key" => "cc14", 'name' => "Does not seek attention/approval of teacher inappropriately."],
    ['order' => 150, 'area_name' => "Classroom Conformity", "key" => "cc15", 'name' => "Does not throw/flick objects in class."],
    ['order' => 160, 'area_name' => "Classroom Conformity", "key" => "cc16", 'name' => "Does not talk inappropriately in class."],
    ['order' => 170, 'area_name' => "Classroom Conformity", "key" => "cc17", 'name' => "Does not need constant supervision."],
    ['order' => 180, 'area_name' => "Classroom Conformity", "key" => "cc18", 'name' => "Does not interrupt when teacher is talking."],
    ['order' => 190, 'area_name' => "Classroom Conformity", "key" => "cc19", 'name' => "Does not take belongings of others."],
    ['order' => 200, 'area_name' => "Classroom Conformity", "key" => "cc20", 'name' => "Accepts change in routine."],
    ['order' => 210, 'area_name' => "Classroom Conformity", "key" => "cc21", 'name' => "Is not lethargic and tired in class."],
    ['order' => 220, 'area_name' => "Classroom Conformity", "key" => "cc22", 'name' => "Does not try to copy work of others."],
    ['order' => 230, 'area_name' => "Classroom Conformity", "key" => "cc23", 'name' => "Has the required materials."],
    ['order' => 240, 'area_name' => "Classroom Conformity", "key" => "cc24", 'name' => "Leaves classroom appropriately."],

    ['area_name' => 'Personal independence', 'name' => 'I practice good personal hygiene (e.g. brush teeth, shower regularly, wash hands, etc.)', 'order' => 10],
    ['area_name' => 'Personal independence', 'name' => 'I understand how poor personal hygiene affects relationships with others.', 'order' => 20],
    ['area_name' => 'Personal independence', 'name' => 'I understand the risks associated with using the internet and in particular social media, and know how to safeguard my personal information.', 'order' => 30],
    ['area_name' => 'Personal independence', 'name' => 'I understand the meaning of a healthy, nutritious diet.', 'order' => 40],
    ['area_name' => 'Personal independence', 'name' => 'I know how to keep myself safe in the community and how to find help if I feel I am at risk.', 'order' => 50],
    ['area_name' => 'Personal independence', 'name' => 'I understand social boundaries and that these differ depending on the relationship (e.g. family, friends, girlfriend, employers, etc.)', 'order' => 60],

    ['order' => 10, 'area_name' => 'Daily and living skills', 'name' => 'I can make and receive telephone calls.', ],
    ['order' => 20, 'area_name' => 'Daily and living skills', 'name' => 'I can plan a weekly menu and develop a weekly shopping list within a budget.', ],
    ['order' => 30, 'area_name' => 'Daily and living skills', 'name' => 'I know how to read food labels and expiry dates.', ],
    ['order' => 40, 'area_name' => 'Daily and living skills', 'name' => 'I know how to store food safely.', ],
    ['order' => 50, 'area_name' => 'Daily and living skills', 'name' => 'I know how to use kitchen utensils and appliances.', ],
    ['order' => 60, 'area_name' => 'Daily and living skills', 'name' => 'I know what cleaning products to use for different tasks.', ],
    ['order' => 70, 'area_name' => 'Daily and living skills', 'name' => 'I know how often household chores should be done to keep the home clean.', ],
    ['order' => 80, 'area_name' => 'Daily and living skills', 'name' => 'I know how to properly dispose of rubbish including recycling.', ],
    ['order' => 90, 'area_name' => 'Daily and living skills', 'name' => 'I can perform minor repairs such as change a plug or lightbulb, reset a circuit breaker, etc.', ],
    ['order' => 100, 'area_name' => 'Daily and living skills', 'name' => 'I know how to separate laundry and use a washing machine.', ],
    ['order' => 110, 'area_name' => 'Daily and living skills', 'name' => 'I understand health and safety procedures in the home.', ],
    ['order' => 120, 'area_name' => 'Daily and living skills', 'name' => 'I know how to dress appropriately for the correct occasion.', ],

    ['order' => 10, 'area_name' => 'Money management', 'name' => 'I can pay for items using cash and/or a debit card.', ],
    ['order' => 20, 'area_name' => 'Money management', 'name' => 'I know how to open a bank account and check a bank statement.', ],
    ['order' => 30, 'area_name' => 'Money management', 'name' => 'I know how to use internet banking and an ATM.', ],
    ['order' => 40, 'area_name' => 'Money management', 'name' => 'I understand the risks of payday loans.', ],
    ['order' => 50, 'area_name' => 'Money management', 'name' => 'I understand how credit cards work and the real cost of buying goods on credit.', ],
    ['order' => 60, 'area_name' => 'Money management', 'name' => 'I can read a payslip and understand the difference between gross and net pay.', ],
    ['order' => 70, 'area_name' => 'Money management', 'name' => 'I know how to budget for regular bills.', ],
    ['order' => 80, 'area_name' => 'Money management', 'name' => 'I understand the difference between luxuries and necessities.', ],
    ['order' => 90, 'area_name' => 'Money management', 'name' => 'I understand the costs of owning a car.', ],
    ['order' => 100, 'area_name' => 'Money management', 'name' => 'I know my rights as a consumer.', ],
    ['order' => 110, 'area_name' => 'Money management', 'name' => 'I understand the value of money and how to spot a good deal.', ],
    ['order' => 120, 'area_name' => 'Money management', 'name' => 'I know about benefits I may be entitled to and how to access these.', ],

    ['area_name' => 'Accessing the community', 'name' => 'I can read and understand a bus/train timetable.', 'order' => 10],
    ['area_name' => 'Accessing the community', 'name' => 'I can use public transport independently.', 'order' => 20],
    ['area_name' => 'Accessing the community', 'name' => 'I know how to seek help if my journey is disrupted.', 'order' => 30],
    ['area_name' => 'Accessing the community', 'name' => 'I can plan a journey independently.', 'order' => 40],
    ['area_name' => 'Accessing the community', 'name' => 'I can ensure that I reach my destination on time.', 'order' => 50],
    ['area_name' => 'Accessing the community', 'name' => 'I understand road and pedestrian safety.', 'order' => 60],
    ['area_name' => 'Accessing the community', 'name' => 'I can communicate appropriately in a variety of community settings.', 'order' => 70],
    ['area_name' => 'Accessing the community', 'name' => 'I can conduct myself appropriately in a variety of community settings.', 'order' => 80],
    ['area_name' => 'Accessing the community', 'name' => 'I know how and where to access leisure activities.', 'order' => 90],
    ['area_name' => 'Accessing the community', 'name' => 'I understanding the value of contributing to the community.', 'order' => 100],
    ['area_name' => 'Accessing the community', 'name' => 'I can access public services and be aware of what services are available.', 'order' => 110],
    ['area_name' => 'Accessing the community', 'name' => 'I can research into community events and local clubs in order to attend.', 'order' => 120],

    ['order' => 10, 'area_name' => 'Work ready/employability', 'name' => 'I can participate in work experience/voluntary work.'],
    ['order' => 20, 'area_name' => 'Work ready/employability', 'name' => 'I can complete a job application form.'],
    ['order' => 30, 'area_name' => 'Work ready/employability', 'name' => 'I can write a CV.'],
    ['order' => 40, 'area_name' => 'Work ready/employability', 'name' => 'I can attend a job interview.'],
    ['order' => 50, 'area_name' => 'Work ready/employability', 'name' => 'I can describe my skills and abilities and match these to job/career ideas.'],
    ['order' => 60, 'area_name' => 'Work ready/employability', 'name' => 'I can search for job opportunities online.'],
    ['order' => 70, 'area_name' => 'Work ready/employability', 'name' => 'I know how and where to access job-seeking support such as Find It Out centre, job centre, job brokerage services, etc.'],
    ['order' => 80, 'area_name' => 'Work ready/employability', 'name' => 'I understand the key skills that employers look for.'],
    ['order' => 90, 'area_name' => 'Work ready/employability', 'name' => 'I understand the different pathways to employment.'],
    ['order' => 100, 'area_name' => 'Work ready/employability', 'name' => 'I understand my rights as an employee.'],
    ['order' => 110, 'area_name' => 'Work ready/employability', 'name' => 'I know to arrive at work on time and dress appropriately.'],
    ['order' => 120, 'area_name' => 'Work ready/employability', 'name' => 'I know that my behaviour and attitude can affect whether I keep my job and my chances of promotion.'],

    ['order' => 10, 'area_name' => 'Health and well-being', 'name' => 'I can be resilient to maintain my mental health well being.'],
    ['order' => 20, 'area_name' => 'Health and well-being', 'name' => 'I can recognise signs of mental ill health and know when and how to seek help.'],
    ['order' => 30, 'area_name' => 'Health and well-being', 'name' => 'I can cope with the everyday stresses of life – resolve problems and setbacks and learn from them.'],
    ['order' => 40, 'area_name' => 'Health and well-being', 'name' => 'I can access mental health services (e.g., patient navigation, support groups) and other social services, comprehensive health services, including mental health and counselling services and support groups.'],
    ['order' => 50, 'area_name' => 'Health and well-being', 'name' => 'I can name range of strategies to cope with life stress - Getting physically active, getting enough sleep, eating a healthy diet, having fun/hobbies, yoga/meditation apps.'],
    ['order' => 60, 'area_name' => 'Health and well-being', 'name' => 'I understand the risks associated with using drugs, alcohol or smoking.'],
    ['order' => 70, 'area_name' => 'Health and well-being', 'name' => 'I understand the risks of sexually transmitted infections and how to prevent them.'],
    ['order' => 80, 'area_name' => 'Health and well-being', 'name' => 'I can recognise signs of physical ill health and know when to seek medical attention know how to call the emergency services.'],
    ['order' => 90, 'area_name' => 'Health and well-being', 'name' => 'I know how to treat minor injuries such as cuts, burns, insect bites and splinters.'],
    ['order' => 100, 'area_name' => 'Health and well-being', 'name' => 'I can select appropriate over the counter medication for minor ailments.'],
    ['order' => 110, 'area_name' => 'Health and well-being', 'name' => 'I know where my nearest GP surgery and A&E department are.'],
    ['order' => 120, 'area_name' => 'Health and well-being', 'name' => 'I can order and collect a prescription.'],
    ['order' => 130, 'area_name' => 'Health and well-being', 'name' => 'I can administer regular medication independently.'],
    ['order' => 140, 'area_name' => 'Health and well-being', 'name' => 'I can stay positive in my outlook (language used, self-talk).'],
    ['order' => 150, 'area_name' => 'Health and well-being', 'name' => 'I can recognize when things are too much /overwhelming & I can accept support.'],
    ['order' => 160, 'area_name' => 'Health and well-being', 'name' => 'I can name and share positive characteristics about myself.'],
    ['order' => 170, 'area_name' => 'Health and well-being', 'name' => 'I can develop a work life balance.'],
    ['order' => 180, 'area_name' => 'Health and well-being', 'name' => 'I can make a medical appointment.'],

    ['order' => 10, 'area_name' => 'Learning and development', 'name' => 'I know my realistic career pathways and how to get there.'],
    ['order' => 20, 'area_name' => 'Learning and development', 'name' => 'I know what education and training is required for the job I want.'],
    ['order' => 30, 'area_name' => 'Learning and development', 'name' => 'I know how to find information about further/higher education courses, traineeships and apprenticeships.'],
    ['order' => 40, 'area_name' => 'Learning and development', 'name' => 'I have a realistic view of my education and training options based upon my current levels of achievement.'],
    ['order' => 50, 'area_name' => 'Learning and development', 'name' => 'I know the costs of completing a course of study or training,'],
    ['order' => 60, 'area_name' => 'Learning and development', 'name' => 'I regularly attend my current course(s) and complete my work.'],


  ];

  public function run()
  {
    $areas = collect(self::Observations)->map(function ($obs) {
      $obs['area_id'] = Area::whereName($obs['area_name'])->first()->id;
      $obs['description'] = $obs['area_name'] . ' - ' . $obs['name'];
      unset($obs['area_name']);
      return factory(Observation::class)->create($obs);
    });
  }
}
