<?php

use Illuminate\Database\Seeder;
use App\Area;
use App\Observation;
use LaravelEnso\PermissionManager\app\Models\Permission;

class ObservationSeeder extends Seeder
{
  private const Observations = [
    // primary wheel
    ['order' => 10, 'area_name' => "Self Awareness", "key" => "sa1", 'name' => "Knows when and how to learn effectively."],
    ['order' => 20, 'area_name' => "Self Awareness", "key" => "sa2", 'name' => "Takes responsibility for actions and learning."],
    ['order' => 30, 'area_name' => "Self Awareness", "key" => "sa3", 'name' => "Feels good about the things they do well and accept themselves for who and what they do."],
    ['order' => 40, 'area_name' => "Self Awareness", "key" => "sa4", 'name' => "Recognises when they find something hard to achieve."],
    ['order' => 50, 'area_name' => "Self Awareness", "key" => "sa5", 'name' => "Identifies, recognises and expresses a range of feelings."],
    ['order' => 60, 'area_name' => "Self Awareness", "key" => "sa6", 'name' => "Knows that feelings, thoughts and behaviours are linked."],
    ['order' => 70, 'area_name' => "Self Awareness", "key" => "sa7", 'name' => "Recognises when they are becoming overwhelmed by their feelings."],
    ['order' => 80, 'area_name' => "Self Awareness", "key" => "sa8", 'name' => "Knows that it is ok to have feelings, but not ok to behave in any way they feel like."],
    ['order' => 90, 'area_name' => "Self Awareness", "key" => "sa9", 'name' => "Knows that all feelings, including uncomfortable ones have a purpose and give us information."],
    ['order' => 100, 'area_name' => "Self Awareness", "key" => "sa10", 'name' => "Knows that it natural to be wary of change, and can explain this."],
    ['order' => 110, 'area_name' => "Self Awareness", "key" => "sa11", 'name' => "Knows the difference between showing they are proud and boasting and knows that boasting can be hurtful."],
    ['order' => 120, 'area_name' => "Self Awareness", "key" => "sa12", 'name' => "Can recognise when they are using an excuse instead of finding a way around a problem."],

    ['order' =>  10, 'area_name' => "Managing Feelings", "key" => "mf13", 'name' => "Can stop and think before acting."],
    ['order' =>  20, 'area_name' => "Managing Feelings", "key" => "mf14", 'name' => "Can express a range of feelings in ways that do not hurt themselves or other people."],
    ['order' =>  30, 'area_name' => "Managing Feelings", "key" => "mf15", 'name' => "Understands that the way they express their feelings can change the way other people feel."],
    ['order' =>  40, 'area_name' => "Managing Feelings", "key" => "mf16", 'name' => "Can adapt the way they express their feelings to suit particular situations or people."],
    ['order' =>  50, 'area_name' => "Managing Feelings", "key" => "mf17", 'name' => "Can calm themselves when they choose."],
    ['order' =>  60, 'area_name' => "Managing Feelings", "key" => "mf18", 'name' => "Have a range of strategies for managing their worries and other uncomfortable feelings."],
    ['order' =>  70, 'area_name' => "Managing Feelings", "key" => "mf19", 'name' => "Have a range of strategies for managing their anger."],
    ['order' =>  80, 'area_name' => "Managing Feelings", "key" => "mf20", 'name' => "Understands that changing the way they think about people and events changes the way they feel about them."],
    ['order' =>  90, 'area_name' => "Managing Feelings", "key" => "mf21", 'name' => "Knows that they can seek support from other people when they feel angry, worried or sad."],
    ['order' => 100, 'area_name' => "Managing Feelings", "key" => "mf22", 'name' => "Knows what makes them feel good and knows how to enhance these comfortable feelings."],
    ['order' => 110, 'area_name' => "Managing Feelings", "key" => "mf23", 'name' => "Can feel positive even when things are going wrong."],
    ['order' => 120, 'area_name' => "Managing Feelings", "key" => "mf24", 'name' => "Can disagree with someone without falling out."],

    ['order' => 10, 'area_name' => "Motivation", "key" => "mo25", 'name' => "Can set a challenge or goal, thinking ahead and considering the consequences for others and themselves."],
    ['order' => 20, 'area_name' => "Motivation", "key" => "mo26", 'name' => "Can break a long term plan into smaller achievable steps, plan to overcome obstacles, set success criteria and celebrate when they achieve them."],
    ['order' => 30, 'area_name' => "Motivation", "key" => "mo27", 'name' => "Can choose when and where to direct their attention, concentrate and resist distractions for increasing periods of time."],
    ['order' => 40, 'area_name' => "Motivation", "key" => "mo28", 'name' => "Knows and can overcome some barriers to their learning such as feelings of boredom and frustration and knows when to keep trying or to try something different."],
    ['order' => 50, 'area_name' => "Motivation", "key" => "mo29", 'name' => "Can bounce back after a disappointment or when they have made a mistake or been unsuccessful."],
    ['order' => 60, 'area_name' => "Motivation", "key" => "mo30", 'name' => "Knows how to evaluate their learning and use this to improve future performance."],

    ['order' => 10, 'area_name' => "Empathy", "key" => "em31", 'name' => "Can recognise the feelings of others."],
    ['order' => 20, 'area_name' => "Empathy", "key" => "em32", 'name' => "Knows that all people have feelings but understands that they might experience and show their feelings in different ways or in different circumstances."],
    ['order' => 30, 'area_name' => "Empathy", "key" => "em33", 'name' => "Can understand another person's point of view and understands how they might be feeling."],
    ['order' => 40, 'area_name' => "Empathy", "key" => "em34", 'name' => "Values and respects the thoughts, feelings, beliefs and values of other people."],
    ['order' => 50, 'area_name' => "Empathy", "key" => "em35", 'name' => "Can be supportive to others and tries to help them when they want it."],
    ['order' => 60, 'area_name' => "Empathy", "key" => "em36", 'name' => "Knows that their actions affect other people and can make them feel better or worse."],

    ['order' =>  10, 'area_name' => "Social Skills", "key" => "ss39", 'name' => "Feel that they belong to and are valued in their class, school and community."],
    ['order' =>  20, 'area_name' => "Social Skills", "key" => "ss40", 'name' => "Understands and accepts their rights and responsibilities in school and know how they can take responsibility for making the school a safe and fair place for everyone."],
    ['order' =>  30, 'area_name' => "Social Skills", "key" => "ss41", 'name' => "Knows how to be friendly, can look and sound friendly, be a good listener, give and receive compliments and do kind things for other people."],
    ['order' =>  40, 'area_name' => "Social Skills", "key" => "ss42", 'name' => "Recognises put downs and know how they affect people, so they try not to use them."],
    ['order' =>  50, 'area_name' => "Social Skills", "key" => "ss43", 'name' => "Can make and sustain friendships without hurting people."],
    ['order' =>  60, 'area_name' => "Social Skills", "key" => "ss44", 'name' => "Can work well in a group, cooperating with others to achieve a joint outcome."],
    ['order' =>  70, 'area_name' => "Social Skills", "key" => "ss45", 'name' => "Can resolve conflicts to ensure that everyone feels positive about the outcome."],
    ['order' =>  80, 'area_name' => "Social Skills", "key" => "ss46", 'name' => "Can be assertive when appropriate."],
    ['order' =>  90, 'area_name' => "Social Skills", "key" => "ss47", 'name' => "Can solve problems by thinking of all the options, identifying advantages and disadvantages, choosing a solution and evaluating it later on."],
    ['order' => 100, 'area_name' => "Social Skills", "key" => "ss48", 'name' => "Can make a wise choice with work or behaviour."],
    ['order' => 110, 'area_name' => "Social Skills", "key" => "ss49", 'name' => "Can forgive someone."],
    ['order' => 120, 'area_name' => "Social Skills", "key" => "ss50", 'name' => "Can accept and appreciate people’s friendships."],

    ['order' =>  10, 'area_name' => "Task Orientation", "key" => "to1", 'name' => "Does not refuse to work."],
    ['order' =>  20, 'area_name' => "Task Orientation", "key" => "to2", 'name' => "Starts on time."],
    ['order' =>  30, 'area_name' => "Task Orientation", "key" => "to3", 'name' => "Not distracted by internal events."],
    ['order' =>  40, 'area_name' => "Task Orientation", "key" => "to4", 'name' => "Not distracted by external events."],
    ['order' =>  50, 'area_name' => "Task Orientation", "key" => "to5", 'name' => "Copes well with task frustration."],
    ['order' =>  60, 'area_name' => "Task Orientation", "key" => "to6", 'name' => "Does not begin task impulsively without understanding."],
    ['order' =>  70, 'area_name' => "Task Orientation", "key" => "to7", 'name' => "Shows interest/motivation toward task."],
    ['order' =>  80, 'area_name' => "Task Orientation", "key" => "to8", 'name' => "Willing to try new work."],
    ['order' =>  90, 'area_name' => "Task Orientation", "key" => "to9", 'name' => "Does not avoid work by loss/abuse of task material."],
    ['order' => 100, 'area_name' => "Task Orientation", "key" => "to10", 'name' => "Shows confidence task-wise."],
    ['order' => 110, 'area_name' => "Task Orientation", "key" => "to11", 'name' => "Acceptable level of error."],
    ['order' => 120, 'area_name' => "Task Orientation", "key" => "to12", 'name' => "Corrects work when asked."],
    ['order' => 130, 'area_name' => "Task Orientation", "key" => "to13", 'name' => "Does not require too much help."],
    ['order' => 140, 'area_name' => "Task Orientation", "key" => "to14", 'name' => "Accepts help from teacher."],
    ['order' => 150, 'area_name' => "Task Orientation", "key" => "to15", 'name' => "Asks for help when needed."],
    ['order' => 160, 'area_name' => "Task Orientation", "key" => "to16", 'name' => "Well presented/organised work."],
    ['order' => 170, 'area_name' => "Task Orientation", "key" => "to17", 'name' => "Well organised desk/materials."],
    ['order' => 180, 'area_name' => "Task Orientation", "key" => "to18", 'name' => "Completes task in given time."],

    ['order' => 10, 'area_name' => "Classroom Conformity", "key" => "cc1", 'name' => "Stays in school."],
    ['order' => 20, 'area_name' => "Classroom Conformity", "key" => "cc2", 'name' => "Attends required lessons."],
    ['order' => 30, 'area_name' => "Classroom Conformity", "key" => "cc3", 'name' => "Stays in class."],
    ['order' => 40, 'area_name' => "Classroom Conformity", "key" => "cc4", 'name' => "Is on time to lessons."],
    ['order' => 50, 'area_name' => "Classroom Conformity", "key" => "cc5", 'name' => "Enters classroom appropriately."],
    ['order' => 60, 'area_name' => "Classroom Conformity", "key" => "cc6", 'name' => "Stays in seat in class."],
    ['order' => 70, 'area_name' => "Classroom Conformity", "key" => "cc7", 'name' => "Sits appropriately in seat in class."],
    ['order' => 80, 'area_name' => "Classroom Conformity", "key" => "cc8", 'name' => "Uses school equipment appropriately."],
    ['order' => 90, 'area_name' => "Classroom Conformity", "key" => "cc9", 'name' => "Raises hand when requiring help."],
    ['order' => 100, 'area_name' => "Classroom Conformity", "key" => "cc10", 'name' => "Does not disrupt class if they have to wait."],
    ['order' => 110, 'area_name' => "Classroom Conformity", "key" => "cc11", 'name' => "Is not verbally inappropriate to teacher."],
    ['order' => 120, 'area_name' => "Classroom Conformity", "key" => "cc12", 'name' => "Is not physically inappropriate to teacher."],
    ['order' => 130, 'area_name' => "Classroom Conformity", "key" => "cc13", 'name' => "Is not over-active in class."],
    ['order' => 140, 'area_name' => "Classroom Conformity", "key" => "cc14", 'name' => "Does not seek attention/approval of teacher inappropriately."],
    ['order' => 150, 'area_name' => "Classroom Conformity", "key" => "cc15", 'name' => "Does not throw/flick objects in class."],
    ['order' => 160, 'area_name' => "Classroom Conformity", "key" => "cc16", 'name' => "Does not talk inappropriately in class."],
    ['order' => 170, 'area_name' => "Classroom Conformity", "key" => "cc17", 'name' => "Does not need constant supervision."],
    ['order' => 180, 'area_name' => "Classroom Conformity", "key" => "cc18", 'name' => "Does not interrupt when teacher is talking."],
    ['order' => 190, 'area_name' => "Classroom Conformity", "key" => "cc19", 'name' => "Does not take belongings of others."],
    ['order' => 200, 'area_name' => "Classroom Conformity", "key" => "cc20", 'name' => "Accepts change in routine."],
    ['order' => 210, 'area_name' => "Classroom Conformity", "key" => "cc21", 'name' => "Is not lethargic and tired in class."],
    ['order' => 220, 'area_name' => "Classroom Conformity", "key" => "cc22", 'name' => "Does not try to copy work of others."],
    ['order' => 230, 'area_name' => "Classroom Conformity", "key" => "cc23", 'name' => "Has the required materials."],
    ['order' => 240, 'area_name' => "Classroom Conformity", "key" => "cc24", 'name' => "Leaves classroom appropriately."],

    // secondary wheel
    ['order' => 410, 'area_name' => "Self Awareness", "key" => "sa1", 'name' => "I know I am a unique individual and can tell you what I am like."],
    ['order' => 420, 'area_name' => "Self Awareness", "key" => "sa2", 'name' => "I know my strengths and I feel good about them."],
    ['order' => 430, 'area_name' => "Self Awareness", "key" => "sa3", 'name' => "I know the things I find hard and I can try to get better at them."],
    ['order' => 440, 'area_name' => "Self Awareness", "key" => "sa4", 'name' => "I can tell when I feel proud of myself and I like it when others praise me."],
    ['order' => 450, 'area_name' => "Self Awareness", "key" => "sa5", 'name' => "I know what is important to me and can listen to what other people want from me."],
    ['order' => 460, 'area_name' => "Self Awareness", "key" => "sa6", 'name' => "I can think about my actions and can learn from them."],
    ['order' => 470, 'area_name' => "Self Awareness", "key" => "sa7", 'name' => "I can make sense of what has happened to me and understand how this makes me feel."],
    ['order' => 480, 'area_name' => "Self Awareness", "key" => "sa8", 'name' => "I can tell what I am feeling and can say how I am feeling."],
    ['order' => 490, 'area_name' => "Self Awareness", "key" => "sa9", 'name' => "I know that feelings sometimes 'take over' and know what makes me feel angry or upset."],
    ['order' => 500, 'area_name' => "Self Awareness", "key" => "sa10", 'name' => "I can tell how I am likely to think, feel and behave in different situations."],
    ['order' => 510, 'area_name' => "Self Awareness", "key" => "sa11", 'name' => "I can tell when I have conflicting feelings and know how to cope with this."],
    ['order' => 520, 'area_name' => "Self Awareness", "key" => "sa12", 'name' => "I can use my past experience to make wise choices to plan what to do with learning and relationships."],

    ['order' => 410, 'area_name' => "Managing Feelings", "key" => "mf13", 'name' => "I can express my feelings clearly and openly and appropriately in different situations."],
    ['order' => 420, 'area_name' => "Managing Feelings", "key" => "mf14", 'name' => "I know that how I express my feelings makes a difference to other people and what happens to me."],
    ['order' => 430, 'area_name' => "Managing Feelings", "key" => "mf15", 'name' => "I know some ways to manage strong feelings so that I do not hurt myself and other people."],
    ['order' => 440, 'area_name' => "Managing Feelings", "key" => "mf16", 'name' => "I know what makes me feel good and how to help have a good time in ways that don't hurt myself or other people."],
    ['order' => 450, 'area_name' => "Managing Feelings", "key" => "mf17", 'name' => "I know that how I feel makes a difference to my health and know how to keep myself well and happy."],
    ['order' => 460, 'area_name' => "Managing Feelings", "key" => "mf18", 'name' => "I can reduce, manage or change strong and uncomfortable feelings such as anger, anxiety, stress and jealousy."],

    ['order' => 410, 'area_name' => "Motivation", "key" => "mo19", 'name' => "I can set myself a goal or challenge and know when I have been successful."],
    ['order' => 420, 'area_name' => "Motivation", "key" => "mo20", 'name' => "I can break a long-term plan into small steps."],
    ['order' => 430, 'area_name' => "Motivation", "key" => "mo21", 'name' => "I can anticipate and plan to work around or overcome potential obstacles."],
    ['order' => 440, 'area_name' => "Motivation", "key" => "mo22", 'name' => "I can monitor and evaluate my own performance."],
    ['order' => 450, 'area_name' => "Motivation", "key" => "mo23", 'name' => "I can work towards long-term goals and can wait for a reward."],
    ['order' => 460, 'area_name' => "Motivation", "key" => "mo24", 'name' => "I know how to bring about change in myself and others."],
    ['order' => 470, 'area_name' => "Motivation", "key" => "mo25", 'name' => "I know that mistakes are a part of learning and can bounce back when I feel disappointed or have failed."],
    ['order' => 480, 'area_name' => "Motivation", "key" => "mo26", 'name' => "I can tell when my feelings are getting in the way of learning and know what to do about it."],
    ['order' => 490, 'area_name' => "Motivation", "key" => "mo27", 'name' => "I can attend well and can ignore distractions."],
    ['order' => 500, 'area_name' => "Motivation", "key" => "mo28", 'name' => "I can think about what I have done and learn from my mistakes."],
    ['order' => 510, 'area_name' => "Motivation", "key" => "mo29", 'name' => "I can stay optimistic and am positive when I try something new."],
    ['order' => 520, 'area_name' => "Motivation", "key" => "mo30", 'name' => "I can take responsibility for myself and my actions."],

    ['order' => 410, 'area_name' => "Empathy", "key" => "em31", 'name' => "I can tell how people are feeling."],
    ['order' => 420, 'area_name' => "Empathy", "key" => "em32", 'name' => "I know that people express their feelings in different ways but that we all have feelings."],
    ['order' => 430, 'area_name' => "Empathy", "key" => "em33", 'name' => "I can tell what other people might be feeling or thinking."],
    ['order' => 440, 'area_name' => "Empathy", "key" => "em34", 'name' => "I can listen to others and I can help them feel better if they are feeling worried or unhappy."],
    ['order' => 450, 'area_name' => "Empathy", "key" => "em35", 'name' => "I respect people from different cultures and backgrounds."],
    ['order' => 460, 'area_name' => "Empathy", "key" => "em36", 'name' => "I know the impact of bullying, prejudice and discrimination on others."],
    ['order' => 470, 'area_name' => "Empathy", "key" => "em37", 'name' => "I can support others with their problems."],
    ['order' => 480, 'area_name' => "Empathy", "key" => "em38", 'name' => "I can feel empathy for others and do things to help."],
    ['order' => 490, 'area_name' => "Empathy", "key" => "new", 'name' => "I understand and accept that the feelings, beliefs and values of other people are important to them."],
    ['order' => 500, 'area_name' => "Empathy", "key" => "new", 'name' => "I can see the world from another person’s point of view"],
    ['order' => 510, 'area_name' => "Empathy", "key" => "new", 'name' => "I can work out how people are feeling through their words, body language, gestures and tone, and pay attention to them."],
    ['order' => 520, 'area_name' => "Empathy", "key" => "new", 'name' => "I have a range of strategies to respond effectively in ways that can help others feel better."],

    ['order' => 410, 'area_name' => "Social Skills", "key" => "ss39", 'name' => "I can communicate with others, listen to them and express my thoughts and feelings."],
    ['order' => 420, 'area_name' => "Social Skills", "key" => "ss40", 'name' => "I can manage my relationships and take account of what other people are thinking and feeling."],
    ['order' => 430, 'area_name' => "Social Skills", "key" => "ss41", 'name' => "I can make wise choices about my relationships."],
    ['order' => 440, 'area_name' => "Social Skills", "key" => "ss42", 'name' => "I can make, keep and break friendships without hurting others."],
    ['order' => 450, 'area_name' => "Social Skills", "key" => "ss43", 'name' => "I can work and learn well in groups and take on different roles."],
    ['order' => 460, 'area_name' => "Social Skills", "key" => "ss44", 'name' => "I know my rights and responsibilities in the many groups I belong to (family, school, friends etc.)"],
    ['order' => 470, 'area_name' => "Social Skills", "key" => "ss45", 'name' => "I can act independently and keep my friends."],
    ['order' => 480, 'area_name' => "Social Skills", "key" => "ss46", 'name' => "I can give feedback to others and can listen to and use feedback from them."],
    ['order' => 490, 'area_name' => "Social Skills", "key" => "ss47", 'name' => "I can solve problems and resolve conflicts with other people."],
    ['order' => 500, 'area_name' => "Social Skills", "key" => "ss48", 'name' => "I can tell when I have been successful or unsuccessful in solving a problem and can make wise choices."],
    ['order' => 510, 'area_name' => "Social Skills", "key" => "ss49", 'name' => "I know how to make up with others when we have fallen out."],
    ['order' => 520, 'area_name' => "Social Skills", "key" => "ss50", 'name' => "I can be assertive when appropriate."],
/*
    ['order' => 410, 'area_name' => "Task Orientation", "key" => "to1", 'name' => "Does not refuse to work."],
    ['order' => 420, 'area_name' => "Task Orientation", "key" => "to2", 'name' => "Starts on time."],
    ['order' => 430, 'area_name' => "Task Orientation", "key" => "to3", 'name' => "Not distracted by internal events."],
    ['order' => 440, 'area_name' => "Task Orientation", "key" => "to4", 'name' => "Not distracted by external events."],
    ['order' => 450, 'area_name' => "Task Orientation", "key" => "to5", 'name' => "Copes well with task frustration."],
    ['order' => 460, 'area_name' => "Task Orientation", "key" => "to6", 'name' => "Does not begin task impulsively without understanding."],
    ['order' => 470, 'area_name' => "Task Orientation", "key" => "to7", 'name' => "Shows interest/motivation toward task."],
    ['order' => 480, 'area_name' => "Task Orientation", "key" => "to8", 'name' => "Willing to try new work."],
    ['order' => 490, 'area_name' => "Task Orientation", "key" => "to9", 'name' => "Does not avoid work by loss/abuse of task material."],
    ['order' => 500, 'area_name' => "Task Orientation", "key" => "to10", 'name' => "Shows confidence task-wise."],
    ['order' => 510, 'area_name' => "Task Orientation", "key" => "to11", 'name' => "Acceptable level of error."],
    ['order' => 520, 'area_name' => "Task Orientation", "key" => "to12", 'name' => "Corrects work when asked."],
    ['order' => 530, 'area_name' => "Task Orientation", "key" => "to13", 'name' => "Does not require too much help."],
    ['order' => 540, 'area_name' => "Task Orientation", "key" => "to14", 'name' => "Accepts help from teacher."],
    ['order' => 550, 'area_name' => "Task Orientation", "key" => "to15", 'name' => "Asks for help when needed."],
    ['order' => 560, 'area_name' => "Task Orientation", "key" => "to16", 'name' => "Well presented/organised work."],
    ['order' => 570, 'area_name' => "Task Orientation", "key" => "to17", 'name' => "Well organised desk/materials."],
    ['order' => 580, 'area_name' => "Task Orientation", "key" => "to18", 'name' => "Completes task in given time."],

    ['order' => 410, 'area_name' => "Classroom Conformity", "key" => "cc1", 'name' => "Stays in school."],
    ['order' => 420, 'area_name' => "Classroom Conformity", "key" => "cc2", 'name' => "Attends required lessons."],
    ['order' => 430, 'area_name' => "Classroom Conformity", "key" => "cc3", 'name' => "Stays in class."],
    ['order' => 440, 'area_name' => "Classroom Conformity", "key" => "cc4", 'name' => "Is on time to lessons."],
    ['order' => 450, 'area_name' => "Classroom Conformity", "key" => "cc5", 'name' => "Enters classroom appropriately."],
    ['order' => 460, 'area_name' => "Classroom Conformity", "key" => "cc6", 'name' => "Stays in seat in class."],
    ['order' => 470, 'area_name' => "Classroom Conformity", "key" => "cc7", 'name' => "Sits appropriately in seat in class."],
    ['order' => 480, 'area_name' => "Classroom Conformity", "key" => "cc8", 'name' => "Uses school equipment appropriately."],
    ['order' => 490, 'area_name' => "Classroom Conformity", "key" => "cc9", 'name' => "Raises hand when requiring help."],
    ['order' => 500, 'area_name' => "Classroom Conformity", "key" => "cc10", 'name' => "Does not disrupt class if they have to wait."],
    ['order' => 510, 'area_name' => "Classroom Conformity", "key" => "cc11", 'name' => "Is not verbally inappropriate to teacher."],
    ['order' => 520, 'area_name' => "Classroom Conformity", "key" => "cc12", 'name' => "Is not physically inappropriate to teacher."],
    ['order' => 530, 'area_name' => "Classroom Conformity", "key" => "cc13", 'name' => "Is not over-active in class."],
    ['order' => 540, 'area_name' => "Classroom Conformity", "key" => "cc14", 'name' => "Does not seek attention/approval of teacher inappropriately."],
    ['order' => 550, 'area_name' => "Classroom Conformity", "key" => "cc15", 'name' => "Does not throw/flick objects in class."],
    ['order' => 560, 'area_name' => "Classroom Conformity", "key" => "cc16", 'name' => "Does not talk inappropriately in class."],
    ['order' => 570, 'area_name' => "Classroom Conformity", "key" => "cc17", 'name' => "Does not need constant supervision."],
    ['order' => 580, 'area_name' => "Classroom Conformity", "key" => "cc18", 'name' => "Does not interrupt when teacher is talking."],
    ['order' => 590, 'area_name' => "Classroom Conformity", "key" => "cc19", 'name' => "Does not take belongings of others."],
    ['order' => 600, 'area_name' => "Classroom Conformity", "key" => "cc20", 'name' => "Accepts change in routine."],
    ['order' => 610, 'area_name' => "Classroom Conformity", "key" => "cc21", 'name' => "Is not lethargic and tired in class."],
    ['order' => 620, 'area_name' => "Classroom Conformity", "key" => "cc22", 'name' => "Does not try to copy work of others."],
    ['order' => 630, 'area_name' => "Classroom Conformity", "key" => "cc23", 'name' => "Has the required materials."],
    ['order' => 640, 'area_name' => "Classroom Conformity", "key" => "cc24", 'name' => "Leaves classroom appropriately."],
*/

    //Keyworker wheel
    ['order' => 10, 'area_name' => "Personal Hygiene and Care", "key" => "kp1", 'name' => "Washes his hands and face properly."],
    ['order' => 10, 'area_name' => "Personal Hygiene and Care", "key" => "kp2", 'name' => "Baths or showers using soap and/or shower gel."],
    ['order' => 10, 'area_name' => "Personal Hygiene and Care", "key" => "kp3", 'name' => "Washes his hair on a daily basis."],
    ['order' => 10, 'area_name' => "Personal Hygiene and Care", "key" => "kp4", 'name' => "Dries himself correctly with a towel."],
    ['order' => 10, 'area_name' => "Personal Hygiene and Care", "key" => "kp5", 'name' => "Uses appropriate deoderants."],
    ['order' => 10, 'area_name' => "Personal Hygiene and Care", "key" => "kp6", 'name' => "Cleans his teeth properly."],
    ['order' => 10, 'area_name' => "Personal Hygiene and Care", "key" => "kp7", 'name' => "Makes his bed properly."],
    ['order' => 10, 'area_name' => "Personal Hygiene and Care", "key" => "kp8", 'name' => "Changes his socks and underwear on a daily basis."],
    ['order' => 10, 'area_name' => "Personal Hygiene and Care", "key" => "kp9", 'name' => "Uses the laundry facilities appropriately."],
    ['order' => 10, 'area_name' => "Personal Hygiene and Care", "key" => "kp10", 'name' => "Wears the appropriate clothes for school and for leisure."],
    ['order' => 10, 'area_name' => "Personal Hygiene and Care", "key" => "kp11", 'name' => "Keeps his bed space clean and tidy."],
    ['order' => 10, 'area_name' => "Personal Hygiene and Care", "key" => "kp12", 'name' => "Has an awareness of the importance of good hygiene."],

    ['order' => 10, 'area_name' => "First Aid and Health", "key" => "kf1", 'name' => "Shows an awareness of danger during leisure activities."],
    ['order' => 10, 'area_name' => "First Aid and Health", "key" => "kf2", 'name' => "Shows an awareness of healthy eating."],
    ['order' => 10, 'area_name' => "First Aid and Health", "key" => "kf3", 'name' => "Eats a healthy diet."],
    ['order' => 10, 'area_name' => "First Aid and Health", "key" => "kf4", 'name' => "Shows an awareness of the importance of taking regular exercise."],
    ['order' => 10, 'area_name' => "First Aid and Health", "key" => "kf5", 'name' => "Participates in regular exercise."],
    ['order' => 10, 'area_name' => "First Aid and Health", "key" => "kf6", 'name' => "Shows an awareness of the use of illegal drugs, alcohol and smoking."],
    ['order' => 10, 'area_name' => "First Aid and Health", "key" => "kf7", 'name' => "Seeks medical help when required and knows where to go."],
    ['order' => 10, 'area_name' => "First Aid and Health", "key" => "kf8", 'name' => "Knows how to contact the emergency services if required."],
    ['order' => 10, 'area_name' => "First Aid and Health", "key" => "kf9", 'name' => "Knows how to use basic first aid."],
    ['order' => 10, 'area_name' => "First Aid and Health", "key" => "kf10", 'name' => "Knows who to contact at night if unwell and where to go to wake them."],
    ['order' => 10, 'area_name' => "First Aid and Health", "key" => "kf11", 'name' => "Shows an awareness of the medication he is on."],
    ['order' => 10, 'area_name' => "First Aid and Health", "key" => "kf12", 'name' => "Shows an awareness of when his medication should be taken."],

    ['order' => 10, 'area_name' => "Emotions", "key" => "ke1", 'name' => "Can empathise with others."],
    ['order' => 10, 'area_name' => "Emotions", "key" => "ke2", 'name' => "Shows remorse or guilt."],
    ['order' => 10, 'area_name' => "Emotions", "key" => "ke3", 'name' => "Has the ability to relax."],
    ['order' => 10, 'area_name' => "Emotions", "key" => "ke4", 'name' => "has the ability to display his emotions appropriately."],
    ['order' => 10, 'area_name' => "Emotions", "key" => "ke5", 'name' => "has the ability to discuss his feelings."],
    ['order' => 10, 'area_name' => "Emotions", "key" => "ke6", 'name' => "Has a positive self-concept."],
    ['order' => 10, 'area_name' => "Emotions", "key" => "ke7", 'name' => "Uses his strategies for anger/frustration."],
    ['order' => 10, 'area_name' => "Emotions", "key" => "ke8", 'name' => "Uses his strategies for aggression and violence."],
    ['order' => 10, 'area_name' => "Emotions", "key" => "ke9", 'name' => "Understands and adapts to change."],
    ['order' => 10, 'area_name' => "Emotions", "key" => "ke10", 'name' => "Has the ability to care for others."],
    ['order' => 10, 'area_name' => "Emotions", "key" => "ke11", 'name' => "Acts independently to meet his own needs."],
    ['order' => 10, 'area_name' => "Emotions", "key" => "ke12", 'name' => "Has the ability to cope with stressful situations."],
    ['order' => 10, 'area_name' => "Relationships", "key" => "kr1", 'name' => "Builds positive relationships with peers appropriately."],
    ['order' => 10, 'area_name' => "Relationships", "key" => "kr2", 'name' => "Shares or lends his possessions with his peers."],
    ['order' => 10, 'area_name' => "Relationships", "key" => "kr3", 'name' => "Shows affection, kindness and empathy to others."],
    ['order' => 10, 'area_name' => "Relationships", "key" => "kr4", 'name' => "Keeps in regular contact with his family and friends."],
    ['order' => 10, 'area_name' => "Relationships", "key" => "kr5", 'name' => "Engages in appropriate conversations with peers."],
    ['order' => 10, 'area_name' => "Relationships", "key" => "kr6", 'name' => "Engages in appropriate conversations with adults."],
    ['order' => 10, 'area_name' => "Relationships", "key" => "kr7", 'name' => "Has the ability to initiate conversations."],
    ['order' => 10, 'area_name' => "Relationships", "key" => "kr8", 'name' => "Builds positive relationships with adults appropriately."],
    ['order' => 10, 'area_name' => "Relationships", "key" => "kr9", 'name' => "Can make decisions independently."],
    ['order' => 10, 'area_name' => "Relationships", "key" => "kr10", 'name' => "Shows an awareness of personal space."],
    ['order' => 10, 'area_name' => "Relationships", "key" => "kr11", 'name' => "Takes turns with others."],
    ['order' => 10, 'area_name' => "Relationships", "key" => "kr12", 'name' => "Enjoys the company of others."],
    ['order' => 10, 'area_name' => "Behaviour - verbal", "key" => "kv1", 'name' => "Avoids threatening staff/peers."],
    ['order' => 10, 'area_name' => "Behaviour - verbal", "key" => "kv2", 'name' => "Avoids racially abusing staff/peers."],
    ['order' => 10, 'area_name' => "Behaviour - verbal", "key" => "kv3", 'name' => "Avoids sexualised language."],
    ['order' => 10, 'area_name' => "Behaviour - verbal", "key" => "kv4", 'name' => "Avoids criticising actions and motives of staff/peers."],
    ['order' => 10, 'area_name' => "Behaviour - verbal", "key" => "kv5", 'name' => "Avoids abusive or obscene language."],
    ['order' => 10, 'area_name' => "Behaviour - verbal", "key" => "kv6", 'name' => "Expresses anger in an acceptable manner."],
    ['order' => 10, 'area_name' => "Behaviour - verbal", "key" => "kv7", 'name' => "Appears in control when verbally aggressive."],
    ['order' => 10, 'area_name' => "Behaviour - verbal", "key" => "kv8", 'name' => "Avoids shouting at staff/peers."],
    ['order' => 10, 'area_name' => "Behaviour - verbal", "key" => "kv9", 'name' => "Avoids using inappropriate noises when angry."],
    ['order' => 10, 'area_name' => "Behaviour - verbal", "key" => "kv10", 'name' => "Avoids repetitive words and sentences."],
    ['order' => 10, 'area_name' => "Behaviour - verbal", "key" => "kv11", 'name' => "Speaks in a clear and understandable manner."],
    ['order' => 10, 'area_name' => "Behaviour - verbal", "key" => "kv12", 'name' => "Allows others to express their views/opinions."],
    ['order' => 10, 'area_name' => "Behaviour - damage/physical", "key" => "kd1", 'name' => "Avoids hitting, kicking, punching or heat butting staff/peers."],
    ['order' => 10, 'area_name' => "Behaviour - damage/physical", "key" => "kd2", 'name' => "Avoids using objects as weapons against staff/peers."],
    ['order' => 10, 'area_name' => "Behaviour - damage/physical", "key" => "kd3", 'name' => "Avoids bullying peers."],
    ['order' => 10, 'area_name' => "Behaviour - damage/physical", "key" => "kd4", 'name' => "Stays free from physical aggression."],
    ['order' => 10, 'area_name' => "Behaviour - damage/physical", "key" => "kd5", 'name' => "Avoids inflicting injuries/pain on others."],
    ['order' => 10, 'area_name' => "Behaviour - damage/physical", "key" => "kd6", 'name' => "Avoids inflicting injuries/pain to self."],
    ['order' => 10, 'area_name' => "Behaviour - damage/physical", "key" => "kd7", 'name' => "Avoids damaging his own property."],
    ['order' => 10, 'area_name' => "Behaviour - damage/physical", "key" => "kd8", 'name' => "Avoids damaging others property."],
    ['order' => 10, 'area_name' => "Behaviour - damage/physical", "key" => "kd9", 'name' => "Avoids damaging property outside the school."],
    ['order' => 10, 'area_name' => "Behaviour - damage/physical", "key" => "kd10", 'name' => "Avoids engaging in play fighting."],
    ['order' => 10, 'area_name' => "Behaviour - damage/physical", "key" => "kd11", 'name' => "Respects the personal space of peers."],
    ['order' => 10, 'area_name' => "Behaviour - damage/physical", "key" => "kd12", 'name' => "Respects the personal space of staff."],
    ['order' => 10, 'area_name' => "Confidence", "key" => "kc1", 'name' => "Gives the impression that he has a worth."],
    ['order' => 10, 'area_name' => "Confidence", "key" => "kc2", 'name' => "Expresses a positiveness about his future."],
    ['order' => 10, 'area_name' => "Confidence", "key" => "kc3", 'name' => "Tries to take part in new untried activities."],
    ['order' => 10, 'area_name' => "Confidence", "key" => "kc4", 'name' => "Tackles situations where his skills could be tested."],
    ['order' => 10, 'area_name' => "Confidence", "key" => "kc5", 'name' => "Believes that others have a high opinion of him."],
    ['order' => 10, 'area_name' => "Confidence", "key" => "kc6", 'name' => "Expresses realistic views about his own skills and attributes."],
    ['order' => 10, 'area_name' => "Confidence", "key" => "kc7", 'name' => "Says there is something he can do to change his life."],
    ['order' => 10, 'area_name' => "Confidence", "key" => "kc8", 'name' => "Feels that adults view him in high regard."],
    ['order' => 10, 'area_name' => "Confidence", "key" => "kc9", 'name' => "See things getting better for himself."],
    ['order' => 10, 'area_name' => "Confidence", "key" => "kc10", 'name' => "Seems happy the way things are turning out."],
    ['order' => 10, 'area_name' => "Confidence", "key" => "kc11", 'name' => "Can socialise confidently outside of school."],
    ['order' => 10, 'area_name' => "Confidence", "key" => "kc12", 'name' => "Has the ability to enjoy his successes."],
    ['order' => 10, 'area_name' => "Self-Image", "key" => "ks1", 'name' => "Aggrees with peers view of himself."],
    ['order' => 10, 'area_name' => "Self-Image", "key" => "ks2", 'name' => "Aggrees with adults view of himself."],
    ['order' => 10, 'area_name' => "Self-Image", "key" => "ks3", 'name' => "Has a realistic view of his skills and attributes."],
    ['order' => 10, 'area_name' => "Self-Image", "key" => "ks4", 'name' => "Does not have an over-rated view of himself."],
    ['order' => 10, 'area_name' => "Self-Image", "key" => "ks5", 'name' => "Does not have an exceptionally low opinion of himself."],
    ['order' => 10, 'area_name' => "Self-Image", "key" => "ks6", 'name' => "Feels his behaviour/life is under control."],
    ['order' => 10, 'area_name' => "Self-Image", "key" => "ks7", 'name' => "Does not feel his behaviour/life is controlled by others."],
    ['order' => 10, 'area_name' => "Self-Image", "key" => "ks8", 'name' => "Does not have a confused or changing view of himself."],
    ['order' => 10, 'area_name' => "Self-Image", "key" => "ks9", 'name' => "Does not appear to live in a fantasy world."],
    ['order' => 10, 'area_name' => "Self-Image", "key" => "ks10", 'name' => "Gives the impression of being positive."],
    ['order' => 10, 'area_name' => "Self-Image", "key" => "ks11", 'name' => "Takes pride in his appearance."],
    ['order' => 10, 'area_name' => "Self-Image", "key" => "ks12", 'name' => "Accepts praise from staff."],
    ['order' => 10, 'area_name' => "Accountability and Responsibility", "key" => "ka1", 'name' => "Understands the rules and routines of the school."],
    ['order' => 10, 'area_name' => "Accountability and Responsibility", "key" => "ka2", 'name' => "Accepts constructive criticism from staff/peers."],
    ['order' => 10, 'area_name' => "Accountability and Responsibility", "key" => "ka3", 'name' => "Takes responsibility for his actions when angry or upset."],
    ['order' => 10, 'area_name' => "Accountability and Responsibility", "key" => "ka4", 'name' => "Accepts consequences appropriately."],
    ['order' => 10, 'area_name' => "Accountability and Responsibility", "key" => "ka5", 'name' => "Takes responsibility for his own mistakes."],
    ['order' => 10, 'area_name' => "Accountability and Responsibility", "key" => "ka6", 'name' => "Shows concern for the safety of others."],
    ['order' => 10, 'area_name' => "Accountability and Responsibility", "key" => "ka7", 'name' => "Manages his anger/aggression appropriately."],
    ['order' => 10, 'area_name' => "Accountability and Responsibility", "key" => "ka8", 'name' => "Manages his language appropriately."],
    ['order' => 10, 'area_name' => "Accountability and Responsibility", "key" => "ka9", 'name' => "Knows his targets."],
    ['order' => 10, 'area_name' => "Accountability and Responsibility", "key" => "ka10", 'name' => "Behaves appropriately in a public place."],
    ['order' => 10, 'area_name' => "Accountability and Responsibility", "key" => "ka11", 'name' => "Asks for help when required."],
    ['order' => 10, 'area_name' => "Accountability and Responsibility", "key" => "ka12", 'name' => "Role models positively."],

    // Work Life Ready
    ['order' => 10, 'area_name' => 'Personal independence', 'name' => 'I practice good personal hygiene (e.g. brush teeth, shower regularly, wash hands, etc.)'],
    ['order' => 20, 'area_name' => 'Personal independence', 'name' => 'I understand how poor personal hygiene affects relationships with others.'],
    ['order' => 30, 'area_name' => 'Personal independence', 'name' => 'I understand the risks associated with using the internet and in particular social media, and know how to safeguard my personal information.'],
    ['order' => 40, 'area_name' => 'Personal independence', 'name' => 'I understand the meaning of a healthy, nutritious diet.'],
    ['order' => 50, 'area_name' => 'Personal independence', 'name' => 'I know how to keep myself safe in the community and how to find help if I feel I am at risk.'],
    ['order' => 60, 'area_name' => 'Personal independence', 'name' => 'I understand social boundaries and that these differ depending on the relationship (e.g. family, friends, girlfriend, employers, etc.)'],

    ['order' => 10, 'area_name' => 'Daily and living skills', 'name' => 'I can make and receive telephone calls.', ],
    ['order' => 20, 'area_name' => 'Daily and living skills', 'name' => 'I can plan a weekly menu and develop a weekly shopping list within a budget.', ],
    ['order' => 30, 'area_name' => 'Daily and living skills', 'name' => 'I know how to read food labels and expiry dates.', ],
    ['order' => 40, 'area_name' => 'Daily and living skills', 'name' => 'I know how to store food safely.', ],
    ['order' => 50, 'area_name' => 'Daily and living skills', 'name' => 'I know how to use kitchen utensils and appliances.', ],
    ['order' => 60, 'area_name' => 'Daily and living skills', 'name' => 'I know what cleaning products to use for different tasks.', ],
    ['order' => 70, 'area_name' => 'Daily and living skills', 'name' => 'I know how often household chores should be done to keep the home clean.', ],
    ['order' => 80, 'area_name' => 'Daily and living skills', 'name' => 'I know how to properly dispose of rubbish including recycling.', ],
    ['order' => 90, 'area_name' => 'Daily and living skills', 'name' => 'I can perform minor repairs such as change a plug or lightbulb, reset a circuit breaker, etc.', ],
    ['order' => 100, 'area_name' => 'Daily and living skills', 'name' => 'I know how to separate laundry and use a washing machine.', ],
    ['order' => 110, 'area_name' => 'Daily and living skills', 'name' => 'I understand health and safety procedures in the home.', ],
    ['order' => 120, 'area_name' => 'Daily and living skills', 'name' => 'I know how to dress appropriately for the correct occasion.', ],

    ['order' => 10, 'area_name' => 'Money management', 'name' => 'I can pay for items using cash and/or a debit card.', ],
    ['order' => 20, 'area_name' => 'Money management', 'name' => 'I know how to open a bank account and check a bank statement.', ],
    ['order' => 30, 'area_name' => 'Money management', 'name' => 'I know how to use internet banking and an ATM.', ],
    ['order' => 40, 'area_name' => 'Money management', 'name' => 'I understand the risks of payday loans.', ],
    ['order' => 50, 'area_name' => 'Money management', 'name' => 'I understand how credit cards work and the real cost of buying goods on credit.', ],
    ['order' => 60, 'area_name' => 'Money management', 'name' => 'I can read a payslip and understand the difference between gross and net pay.', ],
    ['order' => 70, 'area_name' => 'Money management', 'name' => 'I know how to budget for regular bills.', ],
    ['order' => 80, 'area_name' => 'Money management', 'name' => 'I understand the difference between luxuries and necessities.', ],
    ['order' => 90, 'area_name' => 'Money management', 'name' => 'I understand the costs of owning a car.', ],
    ['order' => 100, 'area_name' => 'Money management', 'name' => 'I know my rights as a consumer.', ],
    ['order' => 110, 'area_name' => 'Money management', 'name' => 'I understand the value of money and how to spot a good deal.', ],
    ['order' => 120, 'area_name' => 'Money management', 'name' => 'I know about benefits I may be entitled to and how to access these.', ],

    ['area_name' => 'Accessing the community', 'name' => 'I can read and understand a bus/train timetable.', 'order' => 10],
    ['area_name' => 'Accessing the community', 'name' => 'I can use public transport independently.', 'order' => 20],
    ['area_name' => 'Accessing the community', 'name' => 'I know how to seek help if my journey is disrupted.', 'order' => 30],
    ['area_name' => 'Accessing the community', 'name' => 'I can plan a journey independently.', 'order' => 40],
    ['area_name' => 'Accessing the community', 'name' => 'I can ensure that I reach my destination on time.', 'order' => 50],
    ['area_name' => 'Accessing the community', 'name' => 'I understand road and pedestrian safety.', 'order' => 60],
    ['area_name' => 'Accessing the community', 'name' => 'I can communicate appropriately in a variety of community settings.', 'order' => 70],
    ['area_name' => 'Accessing the community', 'name' => 'I can conduct myself appropriately in a variety of community settings.', 'order' => 80],
    ['area_name' => 'Accessing the community', 'name' => 'I know how and where to access leisure activities.', 'order' => 90],
    ['area_name' => 'Accessing the community', 'name' => 'I understanding the value of contributing to the community.', 'order' => 100],
    ['area_name' => 'Accessing the community', 'name' => 'I can access public services and be aware of what services are available.', 'order' => 110],
    ['area_name' => 'Accessing the community', 'name' => 'I can research into community events and local clubs in order to attend.', 'order' => 120],

    ['order' => 10, 'area_name' => 'Work ready/employability', 'name' => 'I can participate in work experience/voluntary work.'],
    ['order' => 20, 'area_name' => 'Work ready/employability', 'name' => 'I can complete a job application form.'],
    ['order' => 30, 'area_name' => 'Work ready/employability', 'name' => 'I can write a CV.'],
    ['order' => 40, 'area_name' => 'Work ready/employability', 'name' => 'I can attend a job interview.'],
    ['order' => 50, 'area_name' => 'Work ready/employability', 'name' => 'I can describe my skills and abilities and match these to job/career ideas.'],
    ['order' => 60, 'area_name' => 'Work ready/employability', 'name' => 'I can search for job opportunities online.'],
    ['order' => 70, 'area_name' => 'Work ready/employability', 'name' => 'I know how and where to access job-seeking support such as Find It Out centre, job centre, job brokerage services, etc.'],
    ['order' => 80, 'area_name' => 'Work ready/employability', 'name' => 'I understand the key skills that employers look for.'],
    ['order' => 90, 'area_name' => 'Work ready/employability', 'name' => 'I understand the different pathways to employment.'],
    ['order' => 100, 'area_name' => 'Work ready/employability', 'name' => 'I understand my rights as an employee.'],
    ['order' => 110, 'area_name' => 'Work ready/employability', 'name' => 'I know to arrive at work on time and dress appropriately.'],
    ['order' => 120, 'area_name' => 'Work ready/employability', 'name' => 'I know that my behaviour and attitude can affect whether I keep my job and my chances of promotion.'],

    ['order' => 10, 'area_name' => 'Health and well-being', 'name' => 'I can be resilient to maintain my mental health well being.'],
    ['order' => 20, 'area_name' => 'Health and well-being', 'name' => 'I can recognise signs of mental ill health and know when and how to seek help.'],
    ['order' => 30, 'area_name' => 'Health and well-being', 'name' => 'I can cope with the everyday stresses of life – resolve problems and setbacks and learn from them.'],
    ['order' => 40, 'area_name' => 'Health and well-being', 'name' => 'I can access mental health services (e.g., patient navigation, support groups) and other social services, comprehensive health services, including mental health and counselling services and support groups.'],
    ['order' => 50, 'area_name' => 'Health and well-being', 'name' => 'I can name range of strategies to cope with life stress - Getting physically active, getting enough sleep, eating a healthy diet, having fun/hobbies, yoga/meditation apps.'],
    ['order' => 60, 'area_name' => 'Health and well-being', 'name' => 'I understand the risks associated with using drugs, alcohol or smoking.'],
    ['order' => 70, 'area_name' => 'Health and well-being', 'name' => 'I understand the risks of sexually transmitted infections and how to prevent them.'],
    ['order' => 80, 'area_name' => 'Health and well-being', 'name' => 'I can recognise signs of physical ill health and know when to seek medical attention know how to call the emergency services.'],
    ['order' => 90, 'area_name' => 'Health and well-being', 'name' => 'I know how to treat minor injuries such as cuts, burns, insect bites and splinters.'],
    ['order' => 100, 'area_name' => 'Health and well-being', 'name' => 'I can select appropriate over the counter medication for minor ailments.'],
    ['order' => 110, 'area_name' => 'Health and well-being', 'name' => 'I know where my nearest GP surgery and A&E department are.'],
    ['order' => 120, 'area_name' => 'Health and well-being', 'name' => 'I can order and collect a prescription.'],
    ['order' => 130, 'area_name' => 'Health and well-being', 'name' => 'I can administer regular medication independently.'],
    ['order' => 140, 'area_name' => 'Health and well-being', 'name' => 'I can stay positive in my outlook (language used, self-talk).'],
    ['order' => 150, 'area_name' => 'Health and well-being', 'name' => 'I can recognize when things are too much /overwhelming & I can accept support.'],
    ['order' => 160, 'area_name' => 'Health and well-being', 'name' => 'I can name and share positive characteristics about myself.'],
    ['order' => 170, 'area_name' => 'Health and well-being', 'name' => 'I can develop a work life balance.'],
    ['order' => 180, 'area_name' => 'Health and well-being', 'name' => 'I can make a medical appointment.'],

    ['order' => 10, 'area_name' => 'Learning and development', 'name' => 'I know my realistic career pathways and how to get there.'],
    ['order' => 20, 'area_name' => 'Learning and development', 'name' => 'I know what education and training is required for the job I want.'],
    ['order' => 30, 'area_name' => 'Learning and development', 'name' => 'I know how to find information about further/higher education courses, traineeships and apprenticeships.'],
    ['order' => 40, 'area_name' => 'Learning and development', 'name' => 'I have a realistic view of my education and training options based upon my current levels of achievement.'],
    ['order' => 50, 'area_name' => 'Learning and development', 'name' => 'I know the costs of completing a course of study or training,'],
    ['order' => 60, 'area_name' => 'Learning and development', 'name' => 'I regularly attend my current course(s) and complete my work.'],


  ];

  public function run()
  {
    $areas = collect(self::Observations)->map(function ($obs) {
      $obs['area_id'] = Area::whereName($obs['area_name'])->first()->id;
      $obs['description'] = $obs['area_name'] . ' - ' . $obs['name'];
      unset($obs['area_name']);
      return factory(Observation::class)->create($obs);
    });
  }
}
